name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push (main branch → latest)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
            push: true
            tags: robhortonicr/my-apache:latest
  
      - name: Build and push (tagged release → version + latest)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v5
        with:
            push: true
            tags: |
              robhortonicr/my-apache:latest
              robhortonicr/my-apache:${{ github.ref_name }}